name: Bug Report
description: Report a missing language string
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Language string key
      description: en.app.missingstring
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Extra information
      description: If you have any other information, please enter it here
  - type: input
    id: aat-version
    attributes:
      label: Authoring tool version
      description: What version of the Adapt authoring tool are you running?